# Generated by Django 5.1.3 on 2024-11-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0005_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='orderid',
            field=models.IntegerField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
