# Generated by Django 5.1.3 on 2024-11-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0006_delivery_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='orderedimg',
        ),
    ]
