# Generated by Django 5.1.3 on 2024-11-27 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0009_alter_cart_myid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='myid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olxapp.product'),
        ),
    ]
